# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 902a6ebc0e0ad9c2413fdd5c03ab4637234891ccbebe05dedb900a387e6768a0ac0f8994487e95564a5ae064739fe5a80b1441f7b709dc1627e9b2b4cb909e4b

test:
  secret_key_base: 583025e7acf70381dff47dda50d160001a55e8ad616f6f227ce1dacfd4987fefe066df5f5f3ca39b3cd6e0d2a4a2cc4858e0c852a78d4e1698098137e6ace369

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
